### ISSUE TITLE
Docker logs overflow

### ISSUE THREAD

**Issue by wjhdev** [badgerherald/badgerherald.com#253]
Docker logs are eating all available VM space, which is likely the longstanding resource/restart issue the site has been experiencing (e.g. mis-diagnosed in #233)

```
root@prd-badgerherald:/var/lib/docker/containers# du -ch
18G	total 
```

Fix should be simple in compose:

```
services:
  <all>:
    logging:
      options:
        max-size: 1g
```
